### ISSUE TITLE
Structure your project

### ISSUE THREAD

**Issue by lgatto** [gvwilson/10-dm#5]
Before you start, think about the structure of your project
- What type of files will you have: data (raw, processed, ...), source code, figures, outputs, ...
- For each of these categories, create a directory.
- Document all these in your `README` file

```sh
mkdir Project
mkdir Project/data Project/src Project/output Project/figs
touch Project/README
open Project/README
```

During your project, keep the README file up-to-date.

Don't hesitate to change the structure of your project when it evolves, making sure you keep its description in the README up-to-date.

**Comment by gvwilson** [comment]
Does this overlap with/duplicate #1 ?

**Comment by lgatto** [comment]
Mostly, yes. Possibly worth adding something like 

> Don't hesitate to change the structure of your project when it evolves, making sure you keep its description in the README up-to-date.

as sometimes, it's useful to start with a lightweight structure.
